Repository fe-dev-algo/algo-study-team-2024, pull requests merged in 2024-11, with the labels that each got.

#2 [Settings] 깃허브 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/chore.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/ISSUE_TEMPLATE/settings.yml
Labels: Settings

#3 settings: 깃 이슈 템플릿 name 수정
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/ISSUE_TEMPLATE/refactor.yml
Labels: Fix, Settings

#4 [Fix]: 이슈템플릿의 에러 제거
  .github/ISSUE_TEMPLATE/chore.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/ISSUE_TEMPLATE/settings.yml
Labels: Fix, Settings

#5 [Settings]: yaml 파일에서 에러가 나는 특수문자가 포함된 문자열 쌍따옴표로 감싸기
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/ISSUE_TEMPLATE/refactor.yml
Labels: Settings

#6 [Settings] 이슈 템플릿의 난이도 드롭다운 라벨 수정과 누락한 쌍따옴표 적용
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/ISSUE_TEMPLATE/refactor.yml
Labels: Settings

#24 [Settings] PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
  1-implementation/mgYang53/baekjoon-14467.js
  1-implementation/mgYang53/baekjoon-20546.js
Labels: Settings

#17 [Feature] 백준 | 소가 길을 건너간 이유1 구현 알고리즘 풀이
  1-implementation/mgYang53/baekjoon-14467.js
Labels: Feature

#13 [Feature] 백준 | 소가 길을 건나긴 이유 1 구현 알고리즘 풀이
  1-implementation/hyeryeon/14467/index.js
  1-implementation/hyeryeon/14467/input.txt
Labels: Feature

#15 [Feature] 백준 | 기적의 매매법 구현 알고리즘 풀이
  1-implementation/hyeryeon/20546/index.js
  1-implementation/hyeryeon/20546/input.txt
Labels: Feature
